#!/bin/bash

if [ $# -ne 2 ]
then
    echo "Usage: ./populateDydb <Teacher name> <email>"
    exit
fi

aws dynamodb put-item --table-name Course --item '{
            "CourseId": {
                "S": "PyBasic"
            }, 
            "TeacherId": {
                "N": "300"
            }, 
            "Cost": {
                "N": "1000"
            }, 
            "Title": {
                "S": "Python Basic"
            }
        }
'

aws dynamodb put-item --table-name Teacher --item '{
            "email": {
                "S": "'$2'"
            }, 
            "Name": {
                "S": "'$1'"
            }, 
            "Id": {
                "N": "300"
            }
        } 
'
